### ISSUE TITLE
UI einbinden

### ISSUE THREAD

**Issue by batangpinangga** [nacht-des-heiligtums/nachtdesheiligtums.de#22]
Wie weit ist der Stand von der UI zum externen Erstellen von Posts (z.B. von Bene)?
Gibt es die Oberfläche schon?
Können schon Nutzer angelegt werden/ Posts geschrieben werden?

**Comment by straight-shoota** [comment]
Die Oberfläche gibt es schon, Nutzer können über das Netlify-Dashboard verwaltet werden. Bisher fehlt aber noch sämtliche Anpassungen an unser Setup.

**Comment by batangpinangga** [comment]
Aber wenn ich versuche mit unter http://nachtdesheiligtums.de/admin einzuloggen (mit GitHub) lande ich immer wieder auf der cms-netlifly landing page. Irgendwie klappt das noch nicht.

**Comment by straight-shoota** [comment]
Also bei mir klappts, ich komme in die CMS-Oberfläche rein. Taucht aber zwischendurch mal kurz ne Fehlermeldung auf. Also irgendwas scheint da noch nicht zu stimmen.
