### ISSUE TITLE
Einrichtung Instafeed

### ISSUE THREAD

**Issue by straight-shoota** [nacht-des-heiligtums/nachtdesheiligtums.de#4]

**Comment by straight-shoota** [comment]
Code-mäßig ist der Instagram-Feed eingerichtet, aber vom Instagram-Konto nachtdesheiligtums muss noch meine Developer Sandbox-Anfrage akzeptiert und ein Access-Token generiert werden.

**Comment by batangpinangga** [comment]
Wie sieht es denn da aus? Was hat Bene gesagt? @straight-shoota: oder soll ich Bene nochmal fragen?

**Comment by straight-shoota** [comment]
Hab mich jetzt erstmal ums Aufräumen und Fertigmachen konzentriert. Um Instagram kümmer ich mich noch.
