### ISSUE TITLE
Fotogallerie

### ISSUE THREAD

**Issue by batangpinangga** [nacht-des-heiligtums/nachtdesheiligtums.de#9]
Bilder: von alter NdH

**Comment by batangpinangga** [comment]
Mit Bildern der alten NdH

**Comment by batangpinangga** [comment]
Mit Bildern der alten NdH

**Comment by batangpinangga** [comment]
@straight-shoota: Wie schaut es damit aus?

**Comment by straight-shoota** [comment]
Die Flickr-Integration an steht an sich, in templates (oder auch direkt  in posts und pages) können die Tags `flickr_album` und `flickr_photo` verwendet werden. Als erstes Argument muss da jeweils die Album bzw. Photo ID rein.

Es hat jetzt mit dem Album vom NdH-Konto allerdings noch nicht geklappt, da muss ich nochmal genauer nachschauen, woran es hängt. Ich vermute mal an irgendwelchen Zugriffsberechtigungen. Mit meinen Bildern und anderen klappt es aber. Im Zweifel wirds wahrscheinlich am einfachsten sein, ein API-Zugang vom NdH-Konto zu nehmen. Dann sollte das denk ich auch klappen.

**Comment by straight-shoota** [comment]
Ist nun behoben, die Bilder waren nicht öffentlich.

Mit c9aec172f663b25f3f00cad9a433c0711cb031ba ist die Gallerie-Darstellung aktiviert.
